const caseData = {
    "revolution_case": {
        name: "Revolution Case",
        price: 0.60,
        image: "https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNkHpOSV-fRP3axMjBCA59KAtRq6i8FA957P3NcD9B-N_ikpS0m_7zOq-fw20Bv50l37-S896i3VXt_RdrNmqicYfGIVQ6N1_X_VS7x7i-g5C1u8zOm3U36XIi43uMn0G0hAYMMLL_yXpC",
        items: [
            { name: "M4A4 | Temukau", rarity: "red", price: 60.50 },
            { name: "AK-47 | Head Shot", rarity: "red", price: 45.00 },
            { name: "AWP | Duality", rarity: "pink", price: 15.20 },
            { name: "P90 | Neoqueen", rarity: "purple", price: 2.50 },
            { name: "MAC-10 | Sakkaku", rarity: "purple", price: 1.80 },
            { name: "Glock-18 | Umbral Rabbit", rarity: "purple", price: 1.20 },
            { name: "M4A1-S | Emphorosaur-S", rarity: "blue", price: 0.80 },
            { name: "MP9 | Featherweight", rarity: "blue", price: 0.15 },
            { name: "SCAR-20 | Fragments", rarity: "blue", price: 0.20 },
            { name: "P250 | Rebirth", rarity: "blue", price: 0.12 },
            { name: "SG 553 | Cyberforce", rarity: "blue", price: 0.10 },
            { name: "Tec-9 | Rebel", rarity: "blue", price: 0.15 },
            { name: "MAG-7 | Insomnia", rarity: "blue", price: 0.11 },
            { name: "MP5-SD | Liquidation", rarity: "blue", price: 0.14 },
            { name: "R8 Revolver | Banana", rarity: "blue", price: 0.25 },
            { name: "P90 | Desert Warfare", rarity: "blue", price: 0.08 },
            { name: "G3SG1 | Azure", rarity: "blue", price: 0.05 },
            { name: "Dual Berettas | Flora", rarity: "blue", price: 0.09 },
            { name: "★ Sport Gloves | Vice", rarity: "gold", price: 1500.00 },
            { name: "★ Specialist Gloves | Crimson Web", rarity: "gold", price: 850.00 }
        ]
    },
    "cyber_future": {
        name: "Cyber Future Case",
        price: 1.20,
        items: [
            { name: "AK-47 | Neon Rider", rarity: "red", price: 95.00 },
            { name: "AWP | Neo-Noir", rarity: "red", price: 40.00 },
            { name: "M4A4 | Cyber Security", rarity: "pink", price: 22.00 },
            { name: "USP-S | Cortex", rarity: "pink", price: 12.00 },
            { name: "Glock-18 | Wasteland Rebel", rarity: "purple", price: 8.50 },
            { name: "Galil AR | Chromatic Aberration", rarity: "purple", price: 5.00 },
            { name: "MP7 | Bloodsport", rarity: "purple", price: 4.20 },
            { name: "FAMAS | Mecha Industries", rarity: "blue", price: 1.50 },
            { name: "MAC-10 | Oceanic", rarity: "blue", price: 0.40 },
            { name: "P2000 | Acid Etched", rarity: "blue", price: 0.35 },
            { name: "Desert Eagle | Blue Ply", rarity: "blue", price: 0.60 },
            { name: "SSG 08 | Mainframe 001", rarity: "blue", price: 0.10 },
            { name: "Five-SeveN | Scrawl", rarity: "blue", price: 0.08 },
            { name: "MP9 | Modest Threat", rarity: "blue", price: 0.12 },
            { name: "Nova | Exo", rarity: "blue", price: 0.05 },
            { name: "Sawed-Off | Morris", rarity: "blue", price: 0.07 },
            { name: "P90 | Traction", rarity: "blue", price: 0.15 },
            { name: "Dual Berettas | Shred", rarity: "blue", price: 0.11 },
            { name: "★ Karambit | Doppler", rarity: "gold", price: 1800.00 },
            { name: "★ M9 Bayonet | Gamma Doppler", rarity: "gold", price: 2100.00 }
        ]
    },
    "frost_bite": {
        name: "Frost Bite Case",
        price: 0.80,
        items: [
            { name: "AWP | Gungnir", rarity: "red", price: 8000.00 },
            { name: "M4A1-S | Icarus Fell", rarity: "red", price: 450.00 },
            { name: "USP-S | Whiteout", rarity: "pink", price: 90.00 },
            { name: "Glock-18 | Winterized", rarity: "pink", price: 15.00 },
            { name: "AK-47 | Blue Laminate", rarity: "purple", price: 18.00 },
            { name: "Desert Eagle | Cobalt Disruption", rarity: "purple", price: 65.00 },
            { name: "MP9 | Mount Fuji", rarity: "purple", price: 7.00 },
            { name: "Galil AR | Stone Cold", rarity: "blue", price: 2.00 },
            { name: "P250 | Ripple", rarity: "blue", price: 0.50 },
            { name: "SCAR-20 | Blueprint", rarity: "blue", price: 0.30 },
            { name: "FAMAS | Cyanospatter", rarity: "blue", price: 0.20 },
            { name: "G3SG1 | Arctic Camo", rarity: "blue", price: 0.15 },
            { name: "M249 | Blizzard", rarity: "blue", price: 0.10 },
            { name: "MAG-7 | Cobalt Core", rarity: "blue", price: 0.25 },
            { name: "Nova | Polar Mesh", rarity: "blue", price: 0.05 },
            { name: "Dual Berettas | Cobalt Quartz", rarity: "blue", price: 0.40 },
            { name: "SG 553 | Aloha", rarity: "blue", price: 0.12 },
            { name: "R8 Revolver | Skull", rarity: "blue", price: 0.18 },
            { name: "★ Butterfly Knife | Marble Fade", rarity: "gold", price: 2500.00 },
            { name: "★ Skeleton Knife | Case Hardened", rarity: "gold", price: 1200.00 }
        ]
    },
    "inferno_legacy": {
        name: "Inferno Legacy",
        price: 0.50,
        items: [
            { name: "AK-47 | Fire Serpent", rarity: "red", price: 650.00 },
            { name: "AWP | Wildfire", rarity: "red", price: 120.00 },
            { name: "Desert Eagle | Code Red", rarity: "pink", price: 45.00 },
            { name: "M4A4 | Hellfire", rarity: "pink", price: 55.00 },
            { name: "USP-S | Kill Confirmed", rarity: "purple", price: 180.00 },
            { name: "P90 | Shallow Grave", rarity: "purple", price: 4.50 },
            { name: "Glock-18 | Bunsen Burner", rarity: "purple", price: 2.00 },
            { name: "MAC-10 | Heat", rarity: "blue", price: 1.50 },
            { name: "Tec-9 | Isaac", rarity: "blue", price: 3.50 },
            { name: "Sawed-Off | Full Stop", rarity: "blue", price: 0.80 },
            { name: "MP7 | Armor Core", rarity: "blue", price: 0.40 },
            { name: "UMP-45 | Blaze", rarity: "blue", price: 25.00 },
            { name: "Five-SeveN | Flame Test", rarity: "blue", price: 0.20 },
            { name: "SG 553 | Tiger Moth", rarity: "blue", price: 1.20 },
            { name: "CZ75-Auto | Imprint", rarity: "blue", price: 0.15 },
            { name: "MAG-7 | Firestarter", rarity: "blue", price: 0.30 },
            { name: "Galil AR | Firefight", rarity: "blue", price: 0.90 },
            { name: "Aug | Flame Jumper", rarity: "blue", price: 0.10 },
            { name: "★ Talon Knife | Slaughter", rarity: "gold", price: 950.00 },
            { name: "★ Nomad Knife | Crimson Web", rarity: "gold", price: 700.00 }
        ]
    },
    "ocean_depths": {
        name: "Ocean Depths",
        price: 0.45,
        items: [
            { name: "M4A1-S | Blue Phosphor", rarity: "red", price: 550.00 },
            { name: "USP-S | Blueprint", rarity: "red", price: 35.00 },
            { name: "AWP | Sun in Leo", rarity: "pink", price: 25.00 },
            { name: "Glock-18 | Night", rarity: "pink", price: 12.00 },
            { name: "Desert Eagle | Midnight Storm", rarity: "purple", price: 20.00 },
            { name: "MP9 | Pandora's Box", rarity: "purple", price: 80.00 },
            { name: "AK-47 | Aquamarine Revenge", rarity: "purple", price: 75.00 },
            { name: "MAC-10 | Lapis Liquidator", rarity: "blue", price: 0.40 },
            { name: "P250 | Undertow", rarity: "blue", price: 35.00 },
            { name: "FAMAS | Night Borre", rarity: "blue", price: 0.15 },
            { name: "Galil AR | Blue Titanium", rarity: "blue", price: 1.20 },
            { name: "SSG 08 | Abyss", rarity: "blue", price: 2.50 },
            { name: "Tec-9 | Blue Titanium", rarity: "blue", price: 1.80 },
            { name: "MP7 | Cirrus", rarity: "blue", price: 0.30 },
            { name: "SG 553 | Wave Spray", rarity: "blue", price: 1.00 },
            { name: "G3SG1 | Deep Sea", rarity: "blue", price: 0.10 },
            { name: "M249 | Shipping Forecast", rarity: "blue", price: 0.50 },
            { name: "Dual Berettas | Cobalt Quartz", rarity: "blue", price: 0.40 },
            { name: "★ Flip Knife | Bright Water", rarity: "gold", price: 350.00 },
            { name: "★ Huntsman Knife | Lore", rarity: "gold", price: 450.00 }
        ]
    },
    "royal_collection": {
        name: "Royal Collection",
        price: 2.50,
        items: [
            { name: "AWP | Dragon Lore", rarity: "red", price: 12000.00 },
            { name: "M4A4 | The Emperor", rarity: "red", price: 150.00 },
            { name: "AK-47 | The Empress", rarity: "pink", price: 130.00 },
            { name: "USP-S | Royal Blue", rarity: "pink", price: 40.00 },
            { name: "Glock-18 | Royal Legion", rarity: "purple", price: 6.00 },
            { name: "Desert Eagle | Heirloom", rarity: "purple", price: 30.00 },
            { name: "FAMAS | Djinn", rarity: "purple", price: 5.00 },
            { name: "MAC-10 | Gold Brick", rarity: "blue", price: 45.00 },
            { name: "CZ75-Auto | Victoria", rarity: "blue", price: 15.00 },
            { name: "Galil AR | Tuxedo", rarity: "blue", price: 2.50 },
            { name: "MP9 | Rose Iron", rarity: "blue", price: 6.00 },
            { name: "P250 | Franklin", rarity: "blue", price: 4.00 },
            { name: "SSG 08 | Royal Dagger", rarity: "blue", price: 0.80 },
            { name: "SG 553 | Empress", rarity: "blue", price: 1.50 },
            { name: "Tec-9 | Brass", rarity: "blue", price: 8.00 },
            { name: "Five-SeveN | Copper Galaxy", rarity: "blue", price: 7.00 },
            { name: "M4A1-S | Golden Coil", rarity: "blue", price: 85.00 },
            { name: "UMP-45 | Grand Prix", rarity: "blue", price: 0.50 },
            { name: "★ Butterfly Knife | Lore", rarity: "gold", price: 3200.00 },
            { name: "★ Karambit | Gold Gem", rarity: "gold", price: 5000.00 }
        ]
    },
    "dragon_breath": {
        name: "Dragon Breath Case",
        price: 1.50,
        items: [
            { name: "Desert Eagle | Emerald Jörmungandr", rarity: "red", price: 350.00 },
            { name: "AK-47 | Panthera Onca", rarity: "red", price: 280.00 },
            { name: "AWP | Silk Tiger", rarity: "pink", price: 110.00 },
            { name: "USP-S | Ancient Visions", rarity: "pink", price: 45.00 },
            { name: "M4A1-S | Welcome to the Jungle", rarity: "purple", price: 1500.00 },
            { name: "Glock-18 | Franklin", rarity: "purple", price: 35.00 },
            { name: "P90 | Run and Hide", rarity: "purple", price: 25.00 },
            { name: "Galil AR | Dusk Ruins", rarity: "blue", price: 8.00 },
            { name: "MP7 | Tall Grass", rarity: "blue", price: 2.50 },
            { name: "SG 553 | Candy Apple", rarity: "blue", price: 1.20 },
            { name: "MAC-10 | Gold Brick", rarity: "blue", price: 40.00 },
            { name: "Nova | Army Sheen", rarity: "blue", price: 0.15 },
            { name: "R8 Revolver | Night", rarity: "blue", price: 0.30 },
            { name: "Tec-9 | Blast From the Past", rarity: "blue", price: 0.90 },
            { name: "XM1014 | Ancient Lore", rarity: "blue", price: 1.50 },
            { name: "MP9 | Wild Lily", rarity: "blue", price: 800.00 },
            { name: "SSG 08 | Sea Calico", rarity: "blue", price: 90.00 },
            { name: "FAMAS | Sundown", rarity: "blue", price: 5.00 },
            { name: "★ Karambit | Lore", rarity: "gold", price: 1800.00 },
            { name: "★ Ursus Knife | Fade", rarity: "gold", price: 750.00 }
        ]
    },
    "toxic_hazard": {
        name: "Toxic Hazard Case",
        price: 0.75,
        items: [
            { name: "AK-47 | Hydroponic", rarity: "red", price: 1200.00 },
            { name: "M4A4 | Radiation Hazard", rarity: "red", price: 300.00 },
            { name: "USP-S | Road Rash", rarity: "pink", price: 65.00 },
            { name: "Desert Eagle | Sunset Storm", rarity: "pink", price: 180.00 },
            { name: "Glock-18 | Nuclear Garden", rarity: "purple", price: 12.00 },
            { name: "MP9 | Setting Sun", rarity: "purple", price: 8.00 },
            { name: "MAC-10 | Nuclear Garden", rarity: "purple", price: 10.00 },
            { name: "Galil AR | Eco", rarity: "blue", price: 5.00 },
            { name: "P250 | Nuclear Threat", rarity: "blue", price: 45.00 },
            { name: "Sawed-Off | Irradiated Alert", rarity: "blue", price: 1.50 },
            { name: "FAMAS | Styx", rarity: "blue", price: 3.00 },
            { name: "MP7 | Asterion", rarity: "blue", price: 0.80 },
            { name: "Aug | Daedalus", rarity: "blue", price: 0.50 },
            { name: "SG 553 | Fallout Warning", rarity: "blue", price: 2.50 },
            { name: "Tec-9 | Toxic", rarity: "blue", price: 9.00 },
            { name: "XM1014 | Bone Machine", rarity: "blue", price: 2.00 },
            { name: "P90 | Virus", rarity: "blue", price: 3.50 },
            { name: "SSG 08 | Acid Fade", rarity: "blue", price: 1.20 },
            { name: "★ Bayonet | Gamma Doppler", rarity: "gold", price: 1100.00 },
            { name: "★ Bowie Knife | Doppler", rarity: "gold", price: 450.00 }
        ]
    },
    "neon_night": {
        name: "Neon Night Case",
        price: 1.10,
        items: [
            { name: "M4A1-S | Decimator", rarity: "red", price: 25.00 },
            { name: "AK-47 | Point Disarray", rarity: "red", price: 35.00 },
            { name: "AWP | Hyper Beast", rarity: "pink", price: 85.00 },
            { name: "Desert Eagle | Kumicho Dragon", rarity: "pink", price: 30.00 },
            { name: "USP-S | Cyrex", rarity: "purple", price: 15.00 },
            { name: "Glock-18 | Moon Rise", rarity: "purple", price: 4.00 },
            { name: "MP7 | Nemesis", rarity: "purple", price: 8.00 },
            { name: "FAMAS | Pulse", rarity: "blue", price: 3.50 },
            { name: "MAC-10 | Neon Rider", rarity: "blue", price: 12.00 },
            { name: "P250 | Supernova", rarity: "blue", price: 2.00 },
            { name: "Galil AR | Rocket Pop", rarity: "blue", price: 1.50 },
            { name: "SSG 08 | Big Iron", rarity: "blue", price: 12.00 },
            { name: "MP9 | Bioleak", rarity: "blue", price: 0.50 },
            { name: "SG 553 | Pulse", rarity: "blue", price: 4.00 },
            { name: "Tec-9 | Re-Entry", rarity: "blue", price: 1.50 },
            { name: "Five-SeveN | Retrobution", rarity: "blue", price: 3.00 },
            { name: "UMP-45 | Primal Saber", rarity: "blue", price: 5.00 },
            { name: "Dual Berettas | Hemoglobin", rarity: "blue", price: 2.50 },
            { name: "★ Stiletto Knife | Doppler", rarity: "gold", price: 650.00 },
            { name: "★ Falchion Knife | Fade", rarity: "gold", price: 400.00 }
        ]
    },
    "vintage_militia": {
        name: "Vintage Militia Case",
        price: 0.65,
        items: [
            { name: "AK-47 | Fuel Injector", rarity: "red", price: 250.00 },
            { name: "M4A4 | Buzz Kill", rarity: "red", price: 45.00 },
            { name: "AWP | Elite Build", rarity: "pink", price: 20.00 },
            { name: "Desert Eagle | Bronze Deco", rarity: "pink", price: 1.50 },
            { name: "USP-S | Lead Conduit", rarity: "purple", price: 2.50 },
            { name: "Glock-18 | Ironwork", rarity: "purple", price: 1.20 },
            { name: "P250 | Wingshot", rarity: "purple", price: 3.00 },
            { name: "MP9 | Airlock", rarity: "blue", price: 5.00 },
            { name: "FAMAS | Roll Cage", rarity: "blue", price: 12.00 },
            { name: "MAC-10 | Rangeen", rarity: "blue", price: 0.50 },
            { name: "Galil AR | Firefight", rarity: "blue", price: 1.00 },
            { name: "SSG 08 | Ghost Crusader", rarity: "blue", price: 2.50 },
            { name: "MP7 | Akoben", rarity: "blue", price: 0.30 },
            { name: "SG 553 | Atlas", rarity: "blue", price: 0.20 },
            { name: "Tec-9 | Jambiya", rarity: "blue", price: 0.15 },
            { name: "Five-SeveN | Triumvirate", rarity: "blue", price: 3.00 },
            { name: "M249 | Spectre", rarity: "blue", price: 0.20 },
            { name: "Sawed-Off | Limelight", rarity: "blue", price: 1.50 },
            { name: "★ M9 Bayonet | Autotronic", rarity: "gold", price: 1300.00 },
            { name: "★ Gut Knife | Tiger Tooth", rarity: "gold", price: 180.00 }
        ]
    },
    "space_odyssey": {
        name: "Space Odyssey Case",
        price: 1.30,
        items: [
            { name: "AWP | Asiimov", rarity: "red", price: 150.00 },
            { name: "M4A4 | Asiimov", rarity: "red", price: 180.00 },
            { name: "P90 | Asiimov", rarity: "pink", price: 35.00 },
            { name: "AK-47 | Orbit Mk01", rarity: "pink", price: 25.00 },
            { name: "USP-S | Orion", rarity: "purple", price: 65.00 },
            { name: "Glock-18 | Galaxy", rarity: "purple", price: 15.00 },
            { name: "Desert Eagle | Meteorite", rarity: "purple", price: 2.50 },
            { name: "MAC-10 | Ultramarine", rarity: "blue", price: 1.20 },
            { name: "FAMAS | Neural Net", rarity: "blue", price: 1.50 },
            { name: "MP9 | Hypnotic", rarity: "blue", price: 12.00 },
            { name: "Galil AR | Rocket Pop", rarity: "blue", price: 1.50 },
            { name: "SSG 08 | Dark Water", rarity: "blue", price: 0.80 },
            { name: "MP7 | Asterion", rarity: "blue", price: 0.50 },
            { name: "SG 553 | Cyrex", rarity: "blue", price: 8.00 },
            { name: "Tec-9 | Isaac", rarity: "blue", price: 4.00 },
            { name: "Five-SeveN | Nightshade", rarity: "blue", price: 1.00 },
            { name: "Aug | Ricochet", rarity: "blue", price: 0.30 },
            { name: "SCAR-20 | Cyrex", rarity: "blue", price: 3.50 },
            { name: "★ Karambit | Autotronic", rarity: "gold", price: 1600.00 },
            { name: "★ Nomad Knife | Fade", rarity: "gold", price: 900.00 }
        ]
    },
    "jungle_expedition": {
        name: "Jungle Expedition Case",
        price: 0.55,
        items: [
            { name: "AK-47 | Jaguar", rarity: "red", price: 120.00 },
            { name: "M4A1-S | Golden Coil", rarity: "red", price: 110.00 },
            { name: "AWP | Snake Camo", rarity: "pink", price: 45.00 },
            { name: "Desert Eagle | Naga", rarity: "pink", price: 4.00 },
            { name: "USP-S | Para Green", rarity: "purple", price: 5.00 },
            { name: "Glock-18 | Groundwater", rarity: "purple", price: 3.50 },
            { name: "P90 | Death Grip", rarity: "purple", price: 6.00 },
            { name: "MAC-10 | Palm", rarity: "blue", price: 2.50 },
            { name: "FAMAS | Colony", rarity: "blue", price: 0.10 },
            { name: "MP9 | Green Plaid", rarity: "blue", price: 0.30 },
            { name: "Galil AR | Sage Spray", rarity: "blue", price: 0.15 },
            { name: "SSG 08 | Jungle Dashed", rarity: "blue", price: 0.05 },
            { name: "MP7 | Forest Pelt", rarity: "blue", price: 0.08 },
            { name: "SG 553 | Gator Mesh", rarity: "blue", price: 0.20 },
            { name: "Tec-9 | Bamboo Forest", rarity: "blue", price: 1.50 },
            { name: "Five-SeveN | Jungle", rarity: "blue", price: 2.00 },
            { name: "M249 | Jungle", rarity: "blue", price: 0.10 },
            { name: "Sawed-Off | Forest DDPAT", rarity: "blue", price: 0.12 },
            { name: "★ Paracord Knife | Boreal Forest", rarity: "gold", price: 150.00 },
            { name: "★ Survival Knife | Safari Mesh", rarity: "gold", price: 120.00 }
        ]
    },
    "steampunk_gears": {
        name: "Steampunk Gears Case",
        price: 1.45,
        items: [
            { name: "AK-47 | Fuel Injector", rarity: "red", price: 280.00 },
            { name: "M4A4 | Royal Paladin", rarity: "red", price: 95.00 },
            { name: "AWP | Man-o'-war", rarity: "pink", price: 35.00 },
            { name: "Desert Eagle | Bronze Deco", rarity: "pink", price: 1.50 },
            { name: "USP-S | Lead Conduit", rarity: "purple", price: 2.50 },
            { name: "Glock-18 | Brass", rarity: "purple", price: 35.00 },
            { name: "MP7 | Armor Core", rarity: "purple", price: 1.00 },
            { name: "MAC-10 | Copper Borre", rarity: "blue", price: 5.00 },
            { name: "FAMAS | Djinn", rarity: "blue", price: 6.00 },
            { name: "MP9 | Iron Rose", rarity: "blue", price: 7.00 },
            { name: "Galil AR | Tuxedo", rarity: "blue", price: 3.50 },
            { name: "SSG 08 | Abyss", rarity: "blue", price: 2.00 },
            { name: "MP7 | Gunsmoke", rarity: "blue", price: 0.80 },
            { name: "SG 553 | Damascus Steel", rarity: "blue", price: 1.50 },
            { name: "Tec-9 | Brass", rarity: "blue", price: 12.00 },
            { name: "Five-SeveN | Copper Galaxy", rarity: "blue", price: 9.00 },
            { name: "Aug | Aristocrat", rarity: "blue", price: 1.20 },
            { name: "P250 | Cartel", rarity: "blue", price: 15.00 },
            { name: "★ Skeleton Knife | Crimson Web", rarity: "gold", price: 1800.00 },
            { name: "★ Ursus Knife | Marble Fade", rarity: "gold", price: 650.00 }
        ]
    },
    "luxury_goods": {
        name: "Luxury Goods Case",
        price: 3.50,
        items: [
            { name: "AK-47 | Gold Arabesque", rarity: "red", price: 4500.00 },
            { name: "M4A1-S | Knight", rarity: "red", price: 3200.00 },
            { name: "AWP | The Prince", rarity: "pink", price: 4000.00 },
            { name: "Desert Eagle | Fennec Fox", rarity: "pink", price: 600.00 },
            { name: "USP-S | Target Acquired", rarity: "purple", price: 350.00 },
            { name: "Glock-18 | Fade", rarity: "purple", price: 1500.00 },
            { name: "MP9 | Wild Lily", rarity: "purple", price: 1200.00 },
            { name: "MAC-10 | Gold Brick", rarity: "blue", price: 45.00 },
            { name: "FAMAS | Waters of Nephthys", rarity: "blue", price: 150.00 },
            { name: "MP7 | Teal Blossom", rarity: "blue", price: 25.00 },
            { name: "Galil AR | Amber Fade", rarity: "blue", price: 15.00 },
            { name: "SSG 08 | Death's Heads", rarity: "blue", price: 12.00 },
            { name: "P250 | Vino Primo", rarity: "blue", price: 18.00 },
            { name: "SG 553 | Integrale", rarity: "blue", price: 120.00 },
            { name: "Tec-9 | Terrace", rarity: "blue", price: 45.00 },
            { name: "Five-SeveN | Candy Apple", rarity: "blue", price: 40.00 },
            { name: "Aug | Sand Dune", rarity: "blue", price: 0.10 },
            { name: "P90 | Astral Jörmungandr", rarity: "blue", price: 250.00 },
            { name: "★ Butterfly Knife | Gamma Doppler", rarity: "gold", price: 2800.00 },
            { name: "★ Karambit | Fade", rarity: "gold", price: 2200.00 }
        ]
    },
    "pixel_art": {
        name: "Pixel Art Case",
        price: 0.95,
        items: [
            { name: "AK-47 | Frontside Misty", rarity: "red", price: 25.00 },
            { name: "M4A4 | Desolate Space", rarity: "red", price: 20.00 },
            { name: "AWP | Mortis", rarity: "pink", price: 8.00 },
            { name: "Desert Eagle | Directive", rarity: "pink", price: 3.50 },
            { name: "USP-S | Blueprint", rarity: "purple", price: 18.00 },
            { name: "Glock-18 | Bunsen Burner", rarity: "purple", price: 2.00 },
            { name: "MP7 | Akoben", rarity: "purple", price: 0.50 },
            { name: "MAC-10 | Oceanic", rarity: "blue", price: 0.80 },
            { name: "FAMAS | Cyanospatter", rarity: "blue", price: 0.15 },
            { name: "MP9 | Bioleak", rarity: "blue", price: 0.30 },
            { name: "Galil AR | Rocket Pop", rarity: "blue", price: 1.20 },
            { name: "SSG 08 | Mainframe 001", rarity: "blue", price: 0.10 },
            { name: "MP7 | Cirrus", rarity: "blue", price: 0.40 },
            { name: "SG 553 | Aerial", rarity: "blue", price: 0.25 },
            { name: "Tec-9 | Ice Cap", rarity: "blue", price: 0.80 },
            { name: "Five-SeveN | Urban Hazard", rarity: "blue", price: 0.50 },
            { name: "Aug | Ricochet", rarity: "blue", price: 0.30 },
            { name: "P250 | Valence", rarity: "blue", price: 0.90 },
            { name: "★ Shadow Daggers | Marble Fade", rarity: "gold", price: 180.00 },
            { name: "★ Navaja Knife | Tiger Tooth", rarity: "gold", price: 150.00 }
        ]
    },
    "hazard_zone": {
        name: "Hazard Zone Case",
        price: 0.40,
        items: [
            { name: "AK-47 | Rat Rod", rarity: "red", price: 12.00 },
            { name: "M4A4 | Magnesium", rarity: "red", price: 5.00 },
            { name: "AWP | PAW", rarity: "pink", price: 6.00 },
            { name: "Desert Eagle | Light Rail", rarity: "pink", price: 5.50 },
            { name: "USP-S | Flashback", rarity: "purple", price: 2.50 },
            { name: "Glock-18 | Oxide Blaze", rarity: "purple", price: 0.80 },
            { name: "MP7 | Mischief", rarity: "purple", price: 0.40 },
            { name: "MAC-10 | Pipe Down", rarity: "blue", price: 1.20 },
            { name: "FAMAS | Crypsis", rarity: "blue", price: 0.30 },
            { name: "MP9 | Modest Threat", rarity: "blue", price: 0.15 },
            { name: "Galil AR | Signal", rarity: "blue", price: 0.80 },
            { name: "SSG 08 | Necropos", rarity: "blue", price: 0.50 },
            { name: "MP7 | Motherboard", rarity: "blue", price: 0.20 },
            { name: "SG 553 | Danger Close", rarity: "blue", price: 0.40 },
            { name: "Tec-9 | Fubar", rarity: "blue", price: 0.15 },
            { name: "Five-SeveN | Flame Test", rarity: "blue", price: 0.20 },
            { name: "Aug | Sweeper", rarity: "blue", price: 0.10 },
            { name: "P250 | Nevermore", rarity: "blue", price: 0.60 },
            { name: "★ Talon Knife | Urban Masked", rarity: "gold", price: 350.00 },
            { name: "★ Ursus Knife | Scorched", rarity: "gold", price: 140.00 }
        ]
    },
    "horizon_view": {
        name: "Horizon View Case",
        price: 0.85,
        items: [
            { name: "AK-47 | Neon Revolution", rarity: "red", price: 45.00 },
            { name: "M4A4 | Neo-Noir", rarity: "red", price: 40.00 },
            { name: "AWP | Fever Dream", rarity: "pink", price: 12.00 },
            { name: "Desert Eagle | Mecha Industries", rarity: "pink", price: 10.00 },
            { name: "USP-S | Cyrex", rarity: "purple", price: 5.00 },
            { name: "Glock-18 | Wasteland Rebel", rarity: "purple", price: 6.50 },
            { name: "MP7 | Abyssal Apparition", rarity: "purple", price: 3.50 },
            { name: "MAC-10 | Disco Tech", rarity: "blue", price: 15.00 },
            { name: "FAMAS | Eye of Athena", rarity: "blue", price: 5.00 },
            { name: "MP9 | Food Chain", rarity: "blue", price: 6.00 },
            { name: "Galil AR | Sugar Rush", rarity: "blue", price: 10.00 },
            { name: "SSG 08 | Turbo Peek", rarity: "blue", price: 12.00 },
            { name: "MP7 | Powercore", rarity: "blue", price: 1.50 },
            { name: "SG 553 | Colony IV", rarity: "blue", price: 8.00 },
            { name: "Tec-9 | Decimator", rarity: "blue", price: 12.00 },
            { name: "Five-SeveN | Angry Mob", rarity: "blue", price: 10.00 },
            { name: "Aug | Momentum", rarity: "blue", price: 12.00 },
            { name: "P250 | See Ya Later", rarity: "blue", price: 10.00 },
            { name: "★ Kukri Knife | Crimson Web", rarity: "gold", price: 650.00 },
            { name: "★ Stiletto Knife | Fade", rarity: "gold", price: 750.00 }
        ]
    },
    "shattered_web": {
        name: "Shattered Web Case",
        price: 2.10,
        items: [
            { name: "AWP | Containment Breach", rarity: "red", price: 250.00 },
            { name: "AK-47 | Bloodsport", rarity: "red", price: 110.00 },
            { name: "SSG 08 | Blood in the Water", rarity: "pink", price: 85.00 },
            { name: "Desert Eagle | Emerald Jörmungandr", rarity: "pink", price: 350.00 },
            { name: "USP-S | Kill Confirmed", rarity: "purple", price: 180.00 },
            { name: "Glock-18 | Bullet Queen", rarity: "purple", price: 45.00 },
            { name: "MP9 | Hydra", rarity: "purple", price: 12.00 },
            { name: "MAC-10 | Stalker", rarity: "blue", price: 45.00 },
            { name: "FAMAS | Commemoration", rarity: "blue", price: 15.00 },
            { name: "MP7 | Teal Blossom", rarity: "blue", price: 8.00 },
            { name: "Galil AR | Cerberus", rarity: "blue", price: 25.00 },
            { name: "P90 | Nosferatu", rarity: "blue", price: 2.00 },
            { name: "Aug | Arctic Wolf", rarity: "blue", price: 5.00 },
            { name: "SG 553 | Colony IV", rarity: "blue", price: 8.00 },
            { name: "Tec-9 | Decimator", rarity: "blue", price: 12.00 },
            { name: "Five-SeveN | Fairy Tale", rarity: "blue", price: 15.00 },
            { name: "XM1014 | Frost Borre", rarity: "blue", price: 1.20 },
            { name: "P250 | Inferno", rarity: "blue", price: 0.80 },
            { name: "★ Nomad Knife | Case Hardened", rarity: "gold", price: 450.00 },
            { name: "★ Paracord Knife | Slaughter", rarity: "gold", price: 400.00 }
        ]
    },
    "kilowatt_case": {
        name: "Kilowatt Case",
        price: 0.40,
        image: "https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNkHpOSV-fRP3axMjBCA59KAtRq6i8FA957P3NcD9B-N_ikpS0m_7zOq-fw20Bv50l37-S896i3VXt_RdrNmqicYfGIVQ6N1_X_VS7x7i-g5C1u8zOm3U36XIi43uMn0G0hAYMMLL_yXpC",
        items: [
            { name: "AK-47 | Inheritance", rarity: "red", price: 110.00 },
            { name: "AWP | Chrome Cannon", rarity: "red", price: 85.00 },
            { name: "M4A1-S | Black Lotus", rarity: "pink", price: 18.00 },
            { name: "Zeus x27 | Olympus", rarity: "pink", price: 12.00 },
            { name: "USP-S | Jawbreaker", rarity: "purple", price: 5.50 },
            { name: "Glock-18 | Block-18", rarity: "purple", price: 4.20 },
            { name: "MP7 | Just Smile", rarity: "purple", price: 2.50 },
            { name: "MAC-10 | Light Box", rarity: "blue", price: 0.30 },
            { name: "FAMAS | Mixed Camo", rarity: "blue", price: 0.15 },
            { name: "MP9 | Bioleak", rarity: "blue", price: 0.20 },
            { name: "Galil AR | Akihabara Accept", rarity: "blue", price: 1500.00 },
            { name: "SSG 08 | Dezastre", rarity: "blue", price: 1.20 },
            { name: "MP7 | Asterion", rarity: "blue", price: 0.50 },
            { name: "SG 553 | Candy Apple", rarity: "blue", price: 0.80 },
            { name: "Tec-9 | Bamboo Forest", rarity: "blue", price: 0.60 },
            { name: "Five-SeveN | Scrawl", rarity: "blue", price: 0.10 },
            { name: "Aug | Ricochet", rarity: "blue", price: 0.30 },
            { name: "P250 | Cassette", rarity: "blue", price: 0.25 },
            { name: "★ Kukri Knife | Fade", rarity: "gold", price: 950.00 },
            { name: "★ Kukri Knife | Slaughter", rarity: "gold", price: 600.00 }
        ]
    },
    "dreams_nightmares": {
        name: "Dreams & Nightmares",
        price: 0.90,
        image: "https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNkHpOSV-fRP3axMjBCA59KAtRq6i8FA957P3NcD9B-N_ikpS0m_7zOq-fw20Bv50l37-S896i3VXt_RdrNmqicYfGIVQ6N1_X_VS7x7i-g5C1u8zOm3U36XIi43uMn0G0hAYMMLL_yXpC",
        items: [
            { name: "AK-47 | Nightwish", rarity: "red", price: 75.00 },
            { name: "MP9 | Starlight Protector", rarity: "red", price: 30.00 },
            { name: "Dual Berettas | Melondrama", rarity: "pink", price: 10.50 },
            { name: "FAMAS | Rapid Eye Movement", rarity: "pink", price: 8.00 },
            { name: "M4A1-S | Night Terror", rarity: "purple", price: 3.50 },
            { name: "USP-S | Ticket to Hell", rarity: "purple", price: 2.80 },
            { name: "G3SG1 | Dream Glade", rarity: "purple", price: 1.50 },
            { name: "MAC-10 | Ensnared", rarity: "blue", price: 0.25 },
            { name: "PP-Bizon | Space Cat", rarity: "blue", price: 0.40 },
            { name: "MP7 | Abyssal Apparition", rarity: "blue", price: 0.80 },
            { name: "XM1014 | Zombie Offensive", rarity: "blue", price: 0.30 },
            { name: "SCAR-20 | Poultrygeist", rarity: "blue", price: 0.15 },
            { name: "MAG-7 | Foresight", rarity: "blue", price: 0.20 },
            { name: "Sawed-Off | Spirit Board", rarity: "blue", price: 0.35 },
            { name: "P2000 | Lifted", rarity: "blue", price: 0.18 },
            { name: "Five-SeveN | Scrawl", rarity: "blue", price: 0.10 },
            { name: "Aug | Plague", rarity: "blue", price: 0.25 },
            { name: "P250 | Visions", rarity: "blue", price: 15.00 },
            { name: "★ Butterfly Knife | Gamma Doppler", rarity: "gold", price: 2200.00 },
            { name: "★ Shadow Daggers | Lore", rarity: "gold", price: 180.00 }
        ]
    },
    "premium_elite": {
        name: "⭐ Elite Premium",
        price: 850.00,
        items: [
            { name: "★ Butterfly Knife | Marble Fade", rarity: "gold", price: 12500.00 },
            { name: "★ Karambit | Gamma Doppler", rarity: "gold", price: 11000.00 },
            { name: "AWP | Dragon Lore (FT)", rarity: "red", price: 9500.00 },
            { name: "AK-47 | Wild Lotus (WW)", rarity: "red", price: 7800.00 },
            { name: "M4A4 | Howl (Well-Worn)", rarity: "pink", price: 5200.00 },
            { name: "AWP | Gungnir (BS)", rarity: "pink", price: 4800.00 },
            { name: "AK-47 | Gold Arabesque", rarity: "purple", price: 3200.00 },
            { name: "M4A1-S | Welcome to the Jungle", rarity: "purple", price: 2900.00 },
            { name: "Desert Eagle | Fennec Fox", rarity: "purple", price: 1100.00 },
            { name: "Glock-18 | Fade", rarity: "blue", price: 1550.00 },
            { name: "AK-47 | Hydroponic", rarity: "blue", price: 1400.00 },
            { name: "M4A1-S | Knight", rarity: "blue", price: 1250.00 },
            { name: "USP-S | Target Acquired", rarity: "blue", price: 950.00 },
            { name: "MP9 | Wild Lily", rarity: "blue", price: 850.00 },
            { name: "Desert Eagle | Blaze", rarity: "blue", price: 780.00 },
            { name: "AWP | Lightning Strike", rarity: "blue", price: 720.00 },
            { name: "USP-S | Whiteout (FN)", rarity: "blue", price: 680.00 },
            { name: "P250 | Whiteout (FN)", rarity: "blue", price: 650.00 },
            { name: "Glock-18 | Twilight Galaxy", rarity: "blue", price: 620.00 },
            { name: "Desert Eagle | Sunset Storm", rarity: "blue", price: 600.00 }
        ]
    },
    "premium_knife_box": {
        name: "🔪 Pro Knife Case",
        price: 1200.00,
        items: [
            { name: "★ M9 Bayonet | Doppler (Sapphire)", rarity: "gold", price: 12800.00 },
            { name: "★ Karambit | Doppler (Ruby)", rarity: "gold", price: 11500.00 },
            { name: "★ Butterfly Knife | Doppler", rarity: "gold", price: 6500.00 },
            { name: "★ Skeleton Knife | Crimson Web", rarity: "gold", price: 4200.00 },
            { name: "★ M9 Bayonet | Lore", rarity: "pink", price: 3800.00 },
            { name: "★ Karambit | Fade", rarity: "pink", price: 3200.00 },
            { name: "★ Talon Knife | Marble Fade", rarity: "purple", price: 1800.00 },
            { name: "★ Stiletto Knife | Doppler", rarity: "purple", price: 1200.00 },
            { name: "★ M9 Bayonet | Autotronic", rarity: "blue", price: 1100.00 },
            { name: "★ Karambit | Tiger Tooth", rarity: "blue", price: 1050.00 },
            { name: "★ Butterfly Knife | Night", rarity: "blue", price: 950.00 },
            { name: "★ Bayonet | Slaughter", rarity: "blue", price: 880.00 },
            { name: "★ Nomad Knife | Fade", rarity: "blue", price: 820.00 },
            { name: "★ Ursus Knife | Marble Fade", rarity: "blue", price: 780.00 },
            { name: "★ Classic Knife | Crimson Web", rarity: "blue", price: 750.00 },
            { name: "★ Paracord Knife | Slaughter", rarity: "blue", price: 720.00 },
            { name: "★ Survival Knife | Fade", rarity: "blue", price: 680.00 },
            { name: "★ Huntsman Knife | Doppler", rarity: "blue", price: 650.00 },
            { name: "★ Falchion Knife | Marble Fade", rarity: "blue", price: 620.00 },
            { name: "★ Bowie Knife | Marble Fade", rarity: "blue", price: 600.00 }
        ]
    },
    "event_winter_2025": {
        name: "❄️ Winter Holiday 2025",
        price: 60.00,
        items: [
            { name: "★ Butterfly Knife | Doppler (Sapphire)", rarity: "gold", price: 12000.00 },
            { name: "★ Karambit | Blue Steel", rarity: "gold", price: 950.00 },
            { name: "AWP | Gungnir (Battle-Scarred)", rarity: "red", price: 3500.00 },
            { name: "AK-47 | Ice Coaled (StatTrak)", rarity: "red", price: 120.00 },
            { name: "M4A1-S | Icarus Fell", rarity: "pink", price: 450.00 },
            { name: "USP-S | Whiteout", rarity: "pink", price: 180.00 },
            { name: "Glock-18 | Winterized", rarity: "pink", price: 150.00 },
            { name: "Desert Eagle | Cobalt Disruption", rarity: "purple", price: 85.00 },
            { name: "MP9 | Mount Fuji", rarity: "purple", price: 70.00 },
            { name: "Galil AR | Winter Forest", rarity: "purple", price: 65.00 },
            { name: "M4A4 | X-Ray", rarity: "blue", price: 60.00 },
            { name: "AK-47 | Blue Laminate", rarity: "blue", price: 58.00 },
            { name: "P250 | Whiteout", rarity: "blue", price: 55.00 },
            { name: "Five-SeveN | Coolant", rarity: "blue", price: 52.00 },
            { name: "FAMAS | Cyanospatter", rarity: "blue", price: 50.00 },
            { name: "SSG 08 | Ghost Crusader", rarity: "blue", price: 48.00 },
            { name: "MAC-10 | Oceanic", rarity: "blue", price: 45.00 },
            { name: "SG 553 | Aloha", rarity: "blue", price: 42.00 },
            { name: "G3SG1 | Arctic Camo", rarity: "blue", price: 41.00 },
            { name: "Dual Berettas | Cobalt Quartz", rarity: "blue", price: 40.00 },
            { name: "AK-47 | Katowice 2025", rarity: "gold", price: 10000.00 }
        ]
    }
};